name: Optimize images
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Optimize images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ignorePaths: "content/img/avatar_index.gif,quartz/static/**"
          compressOnly: true
          skipInstalls: true

      - name: Commit & Push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CI] Optimize images"
          branch: ${{ github.ref_name }}
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@users.noreply.github.com"
